[project]
name = "playlist-op"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "core",
    "services",
    "utils",
]

[tool.uv.sources]
core = { workspace = true }
services = { workspace = true }
utils = { workspace = true }

[project.scripts]
playlist-op = "playlist_op:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
